# Generated by Django 4.2.7 on 2025-09-26 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_configuration',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('normalized_number', models.CharField(db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('found_results', models.BooleanField(default=False)),
                ('api_source', models.CharField(default='numverify', max_length=50)),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('requests_count', models.PositiveIntegerField(default=1)),
                ('time_window', models.CharField(max_length=20)),
                ('limit_exceeded', models.BooleanField(default=False)),
                ('first_request_at', models.DateTimeField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rate_limit_logs',
                'ordering': ['-last_request_at'],
            },
        ),
        migrations.CreateModel(
            name='APIResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('response_data', models.JSONField()),
                ('api_source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'api_response_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key', 'expires_at'], name='api_respons_cache_k_5e63f1_idx'), models.Index(fields=['expires_at'], name='api_respons_expires_1c38d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_name', models.CharField(default='truthfinder', max_length=100)),
                ('affiliate_url', models.URLField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('click_id', models.CharField(blank=True, max_length=255)),
                ('converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_clicks', to='lookup.searchlog')),
            ],
            options={
                'db_table': 'affiliate_clicks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['phone_number', 'created_at'], name='search_logs_phone_n_aea567_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='search_logs_ip_addr_c0c7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['ip_address', 'endpoint', 'last_request_at'], name='rate_limit__ip_addr_f0d84a_idx'),
        ),
    ]
