# Generated by Django 4.2.7 on 2025-09-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('error_message', models.TextField()),
                ('error_code', models.CharField(blank=True, max_length=20)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('hour_count', models.PositiveIntegerField(default=0)),
                ('day_count', models.PositiveIntegerField(default=0)),
                ('hour_reset', models.DateTimeField(auto_now_add=True)),
                ('day_reset', models.DateTimeField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP Rate Limit',
                'verbose_name_plural': 'IP Rate Limits',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('first_searched', models.DateTimeField(auto_now_add=True)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('spam_reports', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Phone Number Analytics',
                'verbose_name_plural': 'Phone Number Analytics',
                'ordering': ['-search_count'],
            },
        ),
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('line_type', models.CharField(blank=True, max_length=50)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('trend_score', models.FloatField(default=0.0)),
                ('first_searched', models.DateTimeField(auto_now_add=True)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popular Search',
                'verbose_name_plural': 'Popular Searches',
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_searches', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('successful_searches', models.PositiveIntegerField(default=0)),
                ('failed_searches', models.PositiveIntegerField(default=0)),
                ('affiliate_clicks', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Statistics',
                'verbose_name_plural': 'Site Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('accurate', 'Information was accurate'), ('inaccurate', 'Information was incorrect'), ('helpful', 'Very helpful'), ('not_helpful', 'Not helpful'), ('missing_info', 'Missing information'), ('spam_report', 'Report as spam number')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='ratelimitlog',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'ordering': ['key'], 'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configurations'},
        ),
        migrations.RemoveIndex(
            model_name='apiresponsecache',
            name='api_respons_cache_k_5e63f1_idx',
        ),
        migrations.RenameIndex(
            model_name='apiresponsecache',
            new_name='lookup_apir_expires_027c74_idx',
            old_name='api_respons_expires_1c38d8_idx',
        ),
        migrations.RenameIndex(
            model_name='searchlog',
            new_name='lookup_sear_ip_addr_1a2477_idx',
            old_name='search_logs_ip_addr_c0c7c6_idx',
        ),
        migrations.RenameIndex(
            model_name='searchlog',
            new_name='lookup_sear_phone_n_26954b_idx',
            old_name='search_logs_phone_n_aea567_idx',
        ),
        migrations.RemoveField(
            model_name='affiliateclick',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='searchlog',
            name='session_id',
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='conversion_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='affiliateclick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='apiresponsecache',
            name='api_source',
            field=models.CharField(default='numverify', max_length=50),
        ),
        migrations.AlterField(
            model_name='apiresponsecache',
            name='cache_key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='apiresponsecache',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['affiliate_name', 'created_at'], name='lookup_affi_affilia_c6dd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['ip_address', 'created_at'], name='lookup_affi_ip_addr_f22f49_idx'),
        ),
        migrations.AlterModelTable(
            name='affiliateclick',
            table=None,
        ),
        migrations.AlterModelTable(
            name='apiresponsecache',
            table=None,
        ),
        migrations.AlterModelTable(
            name='searchlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='siteconfiguration',
            table=None,
        ),
        migrations.DeleteModel(
            name='RateLimitLog',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='search_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='lookup.searchlog'),
        ),
        migrations.AddIndex(
            model_name='apierrorlog',
            index=models.Index(fields=['api_source', 'created_at'], name='lookup_apie_api_sou_bb5f55_idx'),
        ),
        migrations.AddIndex(
            model_name='apierrorlog',
            index=models.Index(fields=['resolved', 'created_at'], name='lookup_apie_resolve_0ab684_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfeedback',
            unique_together={('search_log', 'ip_address')},
        ),
    ]
