# Generated by Django 4.2.7 on 2025-09-28 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lookup', '0002_apierrorlog_ipratelimit_phonenumberanalytics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('requests_count', models.PositiveIntegerField(default=1)),
                ('time_window', models.CharField(max_length=20)),
                ('limit_exceeded', models.BooleanField(default=False)),
                ('first_request_at', models.DateTimeField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rate_limit_logs',
                'ordering': ['-last_request_at'],
            },
        ),
        migrations.DeleteModel(
            name='APIErrorLog',
        ),
        migrations.DeleteModel(
            name='IPRateLimit',
        ),
        migrations.DeleteModel(
            name='PhoneNumberAnalytics',
        ),
        migrations.DeleteModel(
            name='PopularSearch',
        ),
        migrations.DeleteModel(
            name='SiteStatistics',
        ),
        migrations.AlterUniqueTogether(
            name='userfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='search_log',
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'ordering': ['key']},
        ),
        migrations.RemoveIndex(
            model_name='affiliateclick',
            name='lookup_affi_affilia_c6dd9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='affiliateclick',
            name='lookup_affi_ip_addr_f22f49_idx',
        ),
        migrations.RenameIndex(
            model_name='apiresponsecache',
            new_name='api_respons_expires_1c38d8_idx',
            old_name='lookup_apir_expires_027c74_idx',
        ),
        migrations.RenameIndex(
            model_name='searchlog',
            new_name='search_logs_phone_n_aea567_idx',
            old_name='lookup_sear_phone_n_26954b_idx',
        ),
        migrations.RenameIndex(
            model_name='searchlog',
            new_name='search_logs_ip_addr_c0c7c6_idx',
            old_name='lookup_sear_ip_addr_1a2477_idx',
        ),
        migrations.RemoveField(
            model_name='affiliateclick',
            name='conversion_value',
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affiliateclick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apiresponsecache',
            name='api_source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apiresponsecache',
            name='cache_key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='apiresponsecache',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='apiresponsecache',
            index=models.Index(fields=['cache_key', 'expires_at'], name='api_respons_cache_k_5e63f1_idx'),
        ),
        migrations.AlterModelTable(
            name='affiliateclick',
            table='affiliate_clicks',
        ),
        migrations.AlterModelTable(
            name='apiresponsecache',
            table='api_response_cache',
        ),
        migrations.AlterModelTable(
            name='searchlog',
            table='search_logs',
        ),
        migrations.AlterModelTable(
            name='siteconfiguration',
            table='site_configuration',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['ip_address', 'endpoint', 'last_request_at'], name='rate_limit__ip_addr_f0d84a_idx'),
        ),
    ]
